version: '3'
services:
  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:stable
    volumes:
      - /opt/homeassistant/config:/config
    environment:
      - TZ=Europe/Berlin
    restart: unless-stopped
    network_mode: host

  mosquitto:
    image: eclipse-mosquitto
    container_name: mqtt
    network_mode: host
    restart: unless-stopped
    volumes:
      - /opt/mosquitto/config:/mosquitto/config
      - /opt/mosquitto/data:/mosquitto/data
      - /opt/mosquitto/log:/mosquitto/log
    ports:
      - "1883:1883"
      - "9001:9001"

  influxdb:
    image: influxdb:latest
    ports:
      - '8086:8086'
    volumes:
      - /opt/influxdb:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=db0
      - INFLUXDB_ADMIN_USER=user
      - INFLUXDB_ADMIN_PASSWORD=password

  grafana:
    image: grafana/grafana:latest
    user: "0"
    ports:
      - '3000:3000'
    volumes:
      - /opt/grafana:/var/lib/grafana
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=user
      - GF_SECURITY_ADMIN_PASSWORD=password
